server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 20s
    threads:
      max: 50
      min-spare: 5
polar:
  greeting: Welcome to the local book catalog!
spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 5000
        max-interval: 20000
        multiplier: 1.1
management:
  endpoints:
    web:
      exposure:
        include: refresh